spring:
  application:
    name: herramientas

  datasource:
    url: jdbc:mysql://localhost:3306/db_toolrental_herramientas_vm?createDatabaseIfNotExist=true
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 0
  
springdoc:
  api-docs:
    enabled: true
    path: /herramientas/api-docs
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/