spring:
  application:
    name: herramientas

  datasource:
    url: jdbc:mysql://localhost:3306/bd_multiherramienta_vm
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081
  
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    register-with-eureka: true   # Se registra en el servidor Eureka
    fetch-registry: true         # Obtiene información de otros servicios
    service-url:
      defaultZone: http://localhost:8761/eureka/