server:
  port: 0
  forward-headers-strategy: framework
  
springdoc:
  api-docs:
    enabled: true
    path: /herramientas/api-docs
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

spring:
  application:
    name: herramientas

  datasource:
    url: jdbc:mysql://localhost:3306/db_toolrental_herramientas_vm?createDatabaseIfNotExist=true
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

  profiles:
    active: dev

  mvc:
    cors:
      mappings:
        "/**":
          allowed-origin-patterns: "*"
          allowed-methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
          allowed-headers: "*"
          exposed-headers: "*"
          allow-credentials: false
          max-age: 3600

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/db_toolrental_herramientas_dev?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/db_toolrental_herramientas_test?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/db_toolrental_herramientas_prod?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: "TU_PASSWORD_SEGURO"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none