server:
  port: 8082

spring:
  application:
    name: reservas-service

  datasource:
    url: jdbc:mysql://localhost:3306/bd_reservas_service?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: false

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

services:
  herramientas:
    url: http://localhost:8083/api/v1/herramientas
